/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListUsersResponseDto"][];
                        "application/json": components["schemas"]["ListUsersResponseDto"][];
                        "text/json": components["schemas"]["ListUsersResponseDto"][];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                    "text/json": components["schemas"]["CreateUserRequest"];
                    "application/*+json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreatedResponseDto"];
                        "application/json": components["schemas"]["CreatedResponseDto"];
                        "text/json": components["schemas"]["CreatedResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListAssignableRolesResponseDto"][];
                        "application/json": components["schemas"]["ListAssignableRolesResponseDto"][];
                        "text/json": components["schemas"]["ListAssignableRolesResponseDto"][];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetUserResponseDto"];
                        "application/json": components["schemas"]["GetUserResponseDto"];
                        "text/json": components["schemas"]["GetUserResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserProfileRequest"];
                    "text/json": components["schemas"]["UpdateUserProfileRequest"];
                    "application/*+json": components["schemas"]["UpdateUserProfileRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeUserRoleRequest"];
                    "text/json": components["schemas"]["ChangeUserRoleRequest"];
                    "application/*+json": components["schemas"]["ChangeUserRoleRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetUserPasswordRequest"];
                    "text/json": components["schemas"]["ResetUserPasswordRequest"];
                    "application/*+json": components["schemas"]["ResetUserPasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                    SearchTerm?: string;
                    CompanyId?: string;
                    SortBy?: components["schemas"]["PurchaseSortBy"];
                    SortDescending?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfListPurchasesResponseDto"];
                        "application/json": components["schemas"]["PagedResultOfListPurchasesResponseDto"];
                        "text/json": components["schemas"]["PagedResultOfListPurchasesResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePurchaseRequest"];
                    "text/json": components["schemas"]["CreatePurchaseRequest"];
                    "application/*+json": components["schemas"]["CreatePurchaseRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreatedResponseDto"];
                        "application/json": components["schemas"]["CreatedResponseDto"];
                        "text/json": components["schemas"]["CreatedResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetPurchaseResponseDto"];
                        "application/json": components["schemas"]["GetPurchaseResponseDto"];
                        "text/json": components["schemas"]["GetPurchaseResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchases/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CancelPurchaseRequest"];
                    "text/json": components["schemas"]["CancelPurchaseRequest"];
                    "application/*+json": components["schemas"]["CancelPurchaseRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                    SearchTerm?: string;
                    IsActive?: boolean;
                    SortBy?: components["schemas"]["ProductSortBy"];
                    SortDescending?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfListProductsResponseDto"];
                        "application/json": components["schemas"]["PagedResultOfListProductsResponseDto"];
                        "text/json": components["schemas"]["PagedResultOfListProductsResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProductRequest"];
                    "text/json": components["schemas"]["CreateProductRequest"];
                    "application/*+json": components["schemas"]["CreateProductRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreatedResponseDto"];
                        "application/json": components["schemas"]["CreatedResponseDto"];
                        "text/json": components["schemas"]["CreatedResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/products/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetProductResponseDto"];
                        "application/json": components["schemas"]["GetProductResponseDto"];
                        "text/json": components["schemas"]["GetProductResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProductRequest"];
                    "text/json": components["schemas"]["UpdateProductRequest"];
                    "application/*+json": components["schemas"]["UpdateProductRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListCompaniesResponseDto"][];
                        "application/json": components["schemas"]["ListCompaniesResponseDto"][];
                        "text/json": components["schemas"]["ListCompaniesResponseDto"][];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCompanyRequest"];
                    "text/json": components["schemas"]["CreateCompanyRequest"];
                    "application/*+json": components["schemas"]["CreateCompanyRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreatedResponseDto"];
                        "application/json": components["schemas"]["CreatedResponseDto"];
                        "text/json": components["schemas"]["CreatedResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/companies/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetCompanyResponseDto"];
                        "application/json": components["schemas"]["GetCompanyResponseDto"];
                        "text/json": components["schemas"]["GetCompanyResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCompanyRequest"];
                    "text/json": components["schemas"]["UpdateCompanyRequest"];
                    "application/*+json": components["schemas"]["UpdateCompanyRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogs/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListCountriesResponseDto"][];
                        "application/json": components["schemas"]["ListCountriesResponseDto"][];
                        "text/json": components["schemas"]["ListCountriesResponseDto"][];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogs/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListCurrenciesResponseDto"][];
                        "application/json": components["schemas"]["ListCurrenciesResponseDto"][];
                        "text/json": components["schemas"]["ListCurrenciesResponseDto"][];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogs/igv-affectations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListIgvAffectationsResponseDto"][];
                        "application/json": components["schemas"]["ListIgvAffectationsResponseDto"][];
                        "text/json": components["schemas"]["ListIgvAffectationsResponseDto"][];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogs/tax-document-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListTaxDocumentTypesResponseDto"][];
                        "application/json": components["schemas"]["ListTaxDocumentTypesResponseDto"][];
                        "text/json": components["schemas"]["ListTaxDocumentTypesResponseDto"][];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogs/units-of-measure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListUnitsOfMeasureResponseDto"][];
                        "application/json": components["schemas"]["ListUnitsOfMeasureResponseDto"][];
                        "text/json": components["schemas"]["ListUnitsOfMeasureResponseDto"][];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogs/invoice-price-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListInvoicePriceTypesResponseDto"][];
                        "application/json": components["schemas"]["ListInvoicePriceTypesResponseDto"][];
                        "text/json": components["schemas"]["ListInvoicePriceTypesResponseDto"][];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                    SearchTerm?: string;
                    IsActive?: boolean;
                    PartnerRoleFilter?: components["schemas"]["PartnerRoleFilter"];
                    IdentityDocumentType?: components["schemas"]["IdentityDocumentType"];
                    SortBy?: components["schemas"]["BusinessPartnerSortBy"];
                    SortDescending?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfListBusinessPartnersResponseDto"];
                        "application/json": components["schemas"]["PagedResultOfListBusinessPartnersResponseDto"];
                        "text/json": components["schemas"]["PagedResultOfListBusinessPartnersResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBusinessPartnerRequest"];
                    "text/json": components["schemas"]["CreateBusinessPartnerRequest"];
                    "application/*+json": components["schemas"]["CreateBusinessPartnerRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreatedResponseDto"];
                        "application/json": components["schemas"]["CreatedResponseDto"];
                        "text/json": components["schemas"]["CreatedResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/identity-document-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListIdentityDocumentTypesResponseDto"][];
                        "application/json": components["schemas"]["ListIdentityDocumentTypesResponseDto"][];
                        "text/json": components["schemas"]["ListIdentityDocumentTypesResponseDto"][];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/partners/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/partners/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetBusinessPartnerResponseDto"];
                        "application/json": components["schemas"]["GetBusinessPartnerResponseDto"];
                        "text/json": components["schemas"]["GetBusinessPartnerResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBusinessPartnerRequest"];
                    "text/json": components["schemas"]["UpdateBusinessPartnerRequest"];
                    "application/*+json": components["schemas"]["UpdateBusinessPartnerRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponseDto"];
                        "application/json": components["schemas"]["LoginResponseDto"];
                        "text/json": components["schemas"]["LoginResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetMyProfileResponseDto"];
                        "application/json": components["schemas"]["GetMyProfileResponseDto"];
                        "text/json": components["schemas"]["GetMyProfileResponseDto"];
                    };
                };
                /** @description Error. El cuerpo trae la lista de mensajes para el usuario. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BusinessPartnerSortBy: "Name" | "CreatedAt" | null;
        CancelPurchaseRequest: {
            cancellationReason: null | string;
        };
        ChangeUserRoleRequest: {
            role: null | components["schemas"]["UserRole"];
        };
        /** @enum {unknown} */
        Country: "PE" | "CN";
        CreateBusinessPartnerRequest: {
            identityDocumentType: null | components["schemas"]["IdentityDocumentType"];
            documentNumber: null | string;
            country: null | components["schemas"]["Country"];
            name: null | string;
            isClient: null | boolean;
            isSupplier: null | boolean;
        };
        CreateCompanyRequest: {
            ruc: null | string;
            name: null | string;
        };
        CreatedResponseDto: {
            /** Format: uuid */
            id: string;
        };
        CreateProductRequest: {
            code: null | string;
            name: null | string;
            unitOfMeasure: null | components["schemas"]["UnitOfMeasure"];
            igvAffectation: null | components["schemas"]["IgvAffectation"];
            /** Format: double */
            salePrice: null | number;
        };
        CreatePurchaseLineRequest: {
            /** Format: uuid */
            productId: null | string;
            invoiceIgvAffectation: null | components["schemas"]["IgvAffectation"];
            invoiceUnitOfMeasure: null | components["schemas"]["UnitOfMeasure"];
            /** Format: double */
            invoiceQuantity: null | number;
            /** Format: double */
            invoiceAmount: null | number;
            /** Format: double */
            conversionFactor: null | number;
        };
        CreatePurchaseRequest: {
            /** Format: uuid */
            companyId: null | string;
            taxDocumentType: null | components["schemas"]["TaxDocumentType"];
            serie: null | string;
            number: null | string;
            /** Format: date */
            issueDate: null | string;
            currency: null | components["schemas"]["Currency"];
            /** Format: double */
            exchangeRate: null | number;
            invoicePriceType: null | components["schemas"]["InvoicePriceType"];
            /** Format: uuid */
            supplierId: null | string;
            lines: null | components["schemas"]["CreatePurchaseLineRequest"][];
        };
        CreateUserRequest: {
            name: null | string;
            email: null | string;
            password: null | string;
            role: null | components["schemas"]["UserRole"];
        };
        /** @enum {unknown} */
        Currency: "PEN" | "USD" | null;
        ErrorResponse: {
            errors: string[];
        };
        GetBusinessPartnerResponseDto: {
            /** Format: uuid */
            id: string;
            identityDocumentType: components["schemas"]["IdentityDocumentType"];
            documentNumber: string;
            country: components["schemas"]["Country"];
            name: string;
            isClient: boolean;
            isSupplier: boolean;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            createdByName: null | string;
            /** Format: date-time */
            updatedAt: null | string;
            updatedByName: null | string;
            identityDocumentTypeDescription?: null | string;
            countryName?: null | string;
        };
        GetCompanyResponseDto: {
            /** Format: uuid */
            id: string;
            ruc: string;
            name: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            createdByName: null | string;
            /** Format: date-time */
            updatedAt: null | string;
            updatedByName: null | string;
        };
        GetMyProfileResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            role: components["schemas"]["UserRole"];
            isActive: boolean;
            roleDescription?: null | string;
        };
        GetProductResponseDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            unitOfMeasure: components["schemas"]["UnitOfMeasure"];
            igvAffectation: components["schemas"]["IgvAffectation"];
            /** Format: double */
            salePrice: number;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            createdByName: null | string;
            /** Format: date-time */
            updatedAt: null | string;
            updatedByName: null | string;
            unitOfMeasureDescription?: null | string;
            igvAffectationDescription?: null | string;
        };
        GetPurchaseLineResponseDto: {
            /** Format: int32 */
            lineNumber: number;
            /** Format: uuid */
            productId: string;
            productCode: string;
            productName: string;
            invoiceIgvAffectation: components["schemas"]["IgvAffectation"];
            invoiceUnitOfMeasure: components["schemas"]["UnitOfMeasure"];
            /** Format: double */
            invoiceQuantity: number;
            /** Format: double */
            invoiceUnitAmount: number;
            /** Format: double */
            baseAmount: number;
            /** Format: double */
            igvAmount: number;
            /** Format: double */
            total: number;
            invoiceIgvAffectationDescription?: null | string;
            invoiceUnitOfMeasureDescription?: null | string;
        };
        GetPurchaseResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            companyName: null | string;
            taxDocumentType: components["schemas"]["TaxDocumentType"];
            serie: string;
            number: string;
            /** Format: date */
            issueDate: string;
            currency: components["schemas"]["Currency"];
            /** Format: double */
            exchangeRate: null | number;
            invoicePriceType: components["schemas"]["InvoicePriceType"];
            /** Format: uuid */
            supplierId: string;
            supplierIdentityDocumentType: components["schemas"]["IdentityDocumentType"];
            supplierDocumentNumber: string;
            supplierName: string;
            /** Format: double */
            totalBaseAmount: number;
            /** Format: double */
            totalIgvAmount: number;
            /** Format: double */
            total: number;
            isCancelled: boolean;
            cancellationReason: null | string;
            /** Format: date-time */
            createdAt: string;
            createdByName: null | string;
            /** Format: date-time */
            updatedAt: null | string;
            updatedByName: null | string;
            lines: components["schemas"]["GetPurchaseLineResponseDto"][];
            taxDocumentTypeDescription?: null | string;
            currencyDescription?: null | string;
            invoicePriceTypeDescription?: null | string;
            supplierIdentityDocumentTypeDescription?: null | string;
            fullNumber?: null | string;
        };
        GetUserResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            role: components["schemas"]["UserRole"];
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            createdByName: null | string;
            /** Format: date-time */
            updatedAt: null | string;
            updatedByName: null | string;
            roleDescription?: null | string;
        };
        /** @enum {unknown} */
        IdentityDocumentType: "TributarioExtranjero" | "Dni" | "Ruc";
        /** @enum {unknown} */
        IgvAffectation: "Gravado" | "Inafecto" | null;
        /** @enum {unknown} */
        InvoicePriceType: "UnitValue" | "UnitPrice" | null;
        ListAssignableRolesResponseDto: {
            userRole: components["schemas"]["UserRole"];
            description: string;
        };
        ListBusinessPartnersResponseDto: {
            /** Format: uuid */
            id: string;
            identityDocumentType: components["schemas"]["IdentityDocumentType"];
            documentNumber: string;
            country: components["schemas"]["Country"];
            name: string;
            isClient: boolean;
            isSupplier: boolean;
            isActive: boolean;
            identityDocumentTypeDescription?: null | string;
            countryName?: null | string;
        };
        ListCompaniesResponseDto: {
            /** Format: uuid */
            id: string;
            ruc: string;
            name: string;
            isActive: boolean;
        };
        ListCountriesResponseDto: {
            country: components["schemas"]["Country"];
            name: string;
        };
        ListCurrenciesResponseDto: {
            currency: components["schemas"]["Currency"];
            description: string;
        };
        ListIdentityDocumentTypesResponseDto: {
            identityDocumentType: components["schemas"]["IdentityDocumentType"];
            description: string;
        };
        ListIgvAffectationsResponseDto: {
            igvAffectation: components["schemas"]["IgvAffectation"];
            description: string;
        };
        ListInvoicePriceTypesResponseDto: {
            invoicePriceType: components["schemas"]["InvoicePriceType"];
            description: string;
        };
        ListProductsResponseDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            unitOfMeasure: components["schemas"]["UnitOfMeasure"];
            igvAffectation: components["schemas"]["IgvAffectation"];
            /** Format: double */
            salePrice: number;
            isActive: boolean;
            unitOfMeasureDescription?: null | string;
            igvAffectationDescription?: null | string;
        };
        ListPurchasesResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            companyName: null | string;
            taxDocumentType: components["schemas"]["TaxDocumentType"];
            serie: string;
            number: string;
            /** Format: date */
            issueDate: string;
            currency: components["schemas"]["Currency"];
            /** Format: double */
            exchangeRate: null | number;
            supplierDocumentNumber: string;
            supplierName: string;
            /** Format: double */
            total: number;
            isCancelled: boolean;
            cancellationReason: null | string;
            taxDocumentTypeDescription?: null | string;
            currencyDescription?: null | string;
            fullNumber?: null | string;
        };
        ListTaxDocumentTypesResponseDto: {
            taxDocumentType: components["schemas"]["TaxDocumentType"];
            description: string;
        };
        ListUnitsOfMeasureResponseDto: {
            unitOfMeasure: components["schemas"]["UnitOfMeasure"];
            description: string;
        };
        ListUsersResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            role: components["schemas"]["UserRole"];
            isActive: boolean;
        };
        LoginRequest: {
            email: null | string;
            password: null | string;
        };
        LoginResponseDto: {
            token: string;
        };
        PagedResultOfListBusinessPartnersResponseDto: {
            items: components["schemas"]["ListBusinessPartnersResponseDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages?: number;
            hasNextPage?: boolean;
            hasPreviousPage?: boolean;
        };
        PagedResultOfListProductsResponseDto: {
            items: components["schemas"]["ListProductsResponseDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages?: number;
            hasNextPage?: boolean;
            hasPreviousPage?: boolean;
        };
        PagedResultOfListPurchasesResponseDto: {
            items: components["schemas"]["ListPurchasesResponseDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages?: number;
            hasNextPage?: boolean;
            hasPreviousPage?: boolean;
        };
        /** @enum {unknown} */
        PartnerRoleFilter: "Client" | "Supplier" | null;
        /** @enum {unknown} */
        ProductSortBy: "Name" | "CreatedAt" | null;
        /** @enum {unknown} */
        PurchaseSortBy: "IssueDate" | "SupplierName" | "Total" | "CreatedAt" | null;
        ResetUserPasswordRequest: {
            newPassword: null | string;
        };
        /** @enum {unknown} */
        TaxDocumentType: "Factura" | "Boleta" | null;
        /** @enum {unknown} */
        UnitOfMeasure: "NIU" | "C62" | "DZN" | "BX" | null;
        UpdateBusinessPartnerRequest: {
            identityDocumentType: null | components["schemas"]["IdentityDocumentType"];
            documentNumber: null | string;
            country: null | components["schemas"]["Country"];
            name: null | string;
            isClient: null | boolean;
            isSupplier: null | boolean;
        };
        UpdateCompanyRequest: {
            ruc: null | string;
            name: null | string;
        };
        UpdateProductRequest: {
            code: null | string;
            name: null | string;
            unitOfMeasure: null | components["schemas"]["UnitOfMeasure"];
            igvAffectation: null | components["schemas"]["IgvAffectation"];
            /** Format: double */
            salePrice: null | number;
        };
        UpdateUserProfileRequest: {
            name: null | string;
            email: null | string;
        };
        /** @enum {unknown} */
        UserRole: "SuperAdmin" | "Admin" | "Employee" | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
